# Generated by Django 2.1.8 on 2019-04-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('centent', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '文章表',
                'verbose_name': '文章表',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=32, verbose_name='邮件')),
                ('gender', models.CharField(choices=[(1, '男'), (2, '女')], default=1, max_length=6, verbose_name='性别')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'verbose_name': '用户表',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile', verbose_name='发布者'),
        ),
    ]
