# Generated by Django 2.1.8 on 2019-04-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190402_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='centent',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
    ]
