# Generated by Django 2.1.8 on 2019-04-03 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190403_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=32, verbose_name='备注')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已解决')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '报装申请表',
                'verbose_name': '报装申请表',
            },
        ),
        migrations.CreateModel(
            name='ReportingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='报装类型')),
            ],
            options={
                'verbose_name_plural': '报装类型表',
                'verbose_name': '报装类型表',
            },
        ),
        migrations.CreateModel(
            name='TroubleShoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32, verbose_name='报修详情')),
                ('img', models.ImageField(upload_to='./media/upload_imgs', verbose_name='图片')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('level', models.SmallIntegerField(choices=[(0, '一般'), (0, '紧急'), (0, '较急')], default=0, verbose_name='紧急程度')),
                ('status', models.SmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已解决')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '故障保修表',
                'verbose_name': '故障保修表',
            },
        ),
        migrations.CreateModel(
            name='TroubleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='故障类型')),
            ],
            options={
                'verbose_name_plural': '故障类型表',
                'verbose_name': '故障类型表',
            },
        ),
        migrations.AddField(
            model_name='troubleshoot',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TroubleType', verbose_name='报修类型'),
        ),
        migrations.AddField(
            model_name='troubleshoot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ReportingType', verbose_name='报装类型'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile'),
        ),
    ]
