# Generated by Django 2.1.8 on 2019-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190403_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='user',
            field=models.CharField(max_length=32, verbose_name='报装人'),
        ),
        migrations.AlterField(
            model_name='troubleshoot',
            name='user',
            field=models.CharField(max_length=32, verbose_name='报装人'),
        ),
    ]
