# Generated by Django 2.1.8 on 2019-04-10 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190409_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('pulisher', models.CharField(max_length=32, verbose_name='发布人')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('summary', models.CharField(blank=True, max_length=64, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '公告表',
                'verbose_name': '公告表',
            },
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64, verbose_name='公司名称')),
                ('username', models.CharField(max_length=32, verbose_name='联系人')),
                ('phone', models.CharField(max_length=32, verbose_name='联系人电话')),
                ('weichat', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系人微信')),
                ('sid', models.CharField(blank=True, max_length=64, null=True, verbose_name='UID')),
            ],
            options={
                'verbose_name_plural': '关联用户表',
                'verbose_name': '关联认证表',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='building',
            field=models.SmallIntegerField(choices=[(1, '东照大厦1'), (2, '东照大厦2')], default=1, verbose_name='大厦'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='广州润普', max_length=64, verbose_name='公司名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.SmallIntegerField(blank=True, choices=[(1, '法人'), (2, '财务'), (3, '行政'), (4, '其他')], null=True, verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='floor',
            field=models.SmallIntegerField(choices=[(1, '一楼'), (2, '二楼'), (3, '三楼'), (4, '四楼')], default=1, verbose_name='大厦'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='认证'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '法人'), (2, '财务'), (3, '行政'), (4, '其他')], default=1, verbose_name='所属角色'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room',
            field=models.IntegerField(default='202', verbose_name='房号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='020-000', max_length=32, verbose_name='手机'),
            preserve_default=False,
        ),
    ]
