# Generated by Django 2.1.8 on 2019-04-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190412_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile', verbose_name='报装人'),
        ),
        migrations.AlterField(
            model_name='troubleshoot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserProfile', verbose_name='报修人'),
        ),
    ]
