# Generated by Django 2.1.8 on 2019-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20190415_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshoot',
            name='img',
            field=models.CharField(max_length=64, verbose_name='图片'),
        ),
    ]
